const fs = require('fs');
let content = fs.readFileSync('lock.js', 'utf-8');
let m = content.match(/function 8cCReK.*?\{.*?\}/s);
if (m) console.log(m[0]);
// Wait, '8cCReK' is likely one of the scrambled names generated by the deobfuscator, not in lock.js originally.
// Let's print out what jt3IoMo[tdEyx0(xwy5d8[0x36])] is!
